import { createClient } from '@supabase/supabase-js';

// Client-side Supabase client (uses anon key)
export const supabaseClient = createClient<Database>(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

// Server-side Supabase client (uses service role key for admin operations)
export const supabaseAdmin = createClient<Database>(
  process.env.SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false,
    },
  }
);

// Database types (to be generated by Supabase CLI)
export type Database = {
  public: {
    Tables: {
      businesses: {
        Row: {
          id: string;
          external_id: string;
          name: string;
          category: string | null;
          address: string | null;
          phone: string | null;
          status: string | null;
          opened_date: string | null;
          location: string | null;
          last_seen: string;
          is_active: boolean;
          raw_data: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          external_id: string;
          name: string;
          category?: string | null;
          address?: string | null;
          phone?: string | null;
          status?: string | null;
          opened_date?: string | null;
          location?: string | null;
          last_seen?: string;
          is_active?: boolean;
          raw_data?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          external_id?: string;
          name?: string;
          category?: string | null;
          address?: string | null;
          phone?: string | null;
          status?: string | null;
          opened_date?: string | null;
          location?: string | null;
          last_seen?: string;
          is_active?: boolean;
          raw_data?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
      insights: {
        Row: {
          id: string;
          title: string;
          slug: string;
          content: string;
          summary: string;
          seo_description: string;
          featured_businesses: any[];
          tags: string[];
          category: string;
          published_at: string;
          view_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          title: string;
          slug: string;
          content: string;
          summary: string;
          seo_description: string;
          featured_businesses?: any[];
          tags?: string[];
          category: string;
          published_at?: string;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          title?: string;
          slug?: string;
          content?: string;
          summary?: string;
          seo_description?: string;
          featured_businesses?: any[];
          tags?: string[];
          category?: string;
          published_at?: string;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      subscriptions: {
        Row: {
          id: string;
          user_email: string;
          tier_id: string;
          stripe_customer_id: string;
          stripe_subscription_id: string;
          status: string;
          current_period_start: string;
          current_period_end: string;
          cancel_at_period_end: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_email: string;
          tier_id: string;
          stripe_customer_id: string;
          stripe_subscription_id: string;
          status: string;
          current_period_start: string;
          current_period_end: string;
          cancel_at_period_end?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_email?: string;
          tier_id?: string;
          stripe_customer_id?: string;
          stripe_subscription_id?: string;
          status?: string;
          current_period_start?: string;
          current_period_end?: string;
          cancel_at_period_end?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      api_keys: {
        Row: {
          id: string;
          key: string;
          user_email: string;
          subscription_id: string;
          rate_limit: number;
          requests_count: number;
          last_used: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          key: string;
          user_email: string;
          subscription_id: string;
          rate_limit: number;
          requests_count?: number;
          last_used?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          key?: string;
          user_email?: string;
          subscription_id?: string;
          rate_limit?: number;
          requests_count?: number;
          last_used?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
};
